# Generated by Django 5.0.4 on 2024-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.BooleanField(default=False),
        ),
    ]
