# Generated by Django 5.0.4 on 2024-04-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_body_post_cuerpo_rename_publisher_post_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='editor',
            new_name='publicado',
        ),
    ]
